### ISSUE TITLE
Support custom environments

### ISSUE THREAD

**Issue by wagh311** [jjshoots/PyFlyt#16]
great job!I would like to ask, does the project support custom environments? For example, changing the simulation environment, adding obstacles, etc.?Thanks.

**Comment by jjshoots** [comment]
Of course! That was the intended goal all along. Feel free to look at any of the Gymnasium environments code to see how you can make your own. I am also happy to prpovide assistance and guidance if you have a starting point and an end goal in mind.

**Comment by wagh311** [comment]
Thank you for your reply. My current job is to use MADRL to enable multiple drones to track moving ground targets in a fixed-size area. Specifically, there are several static obstacles in the mission area, and the UAV needs to avoid obstacles and continuously track the target based on the image information obtained by the camera. Do you think I can accomplish this with the help of PyFlyt? Thanks again!

**Comment by jjshoots** [comment]
Yep, that's definitely possible with PyFlyt. I already do something [similar](https://github.com/jjshoots/pyflyt_rail_env) - flying a UAV along a railway while avoiding obstacles along the way. Beyond that, I think an enviroment that you can look at is the QuadX Gates environment. It's not part of the official PyFlyt package since I haven't had the time to ensure that it's learnable yet. But I think you can accomplish what you need by bootstrapping off that environment.

**Comment by wagh311** [comment]
That's really cool, I'll give it a try. Thanks!

**Comment by wagh311** [comment]
OK, thank you very much for your advice!
