### ISSUE TITLE
Rocket Landing Task Fail 

### ISSUE THREAD

**Issue by Pytha11** [jjshoots/PyFlyt#64]
I have tried some RL algorithms, but all of them do not success to land.
Do you have a successful case? Like, use PPO with some specific hyper-parameters.

**Comment by jjshoots** [comment]
I never actually expected anyone to try the rocket landing environment, and I have only gotten it to work in some very rare edge cases.

So TLDR; it's actually not solved. I would be very happy if you want to take over designing a reward structure/sensor scheme for the environment. I can put you on the webpage when it is solved and also acknowledge your contributions in the paper when it is published.

**Comment by Pytha11** [comment]
I would like to contribute to the code, but I need more time to understand the physical dynamics. I think it is still a challenge.
For example, I only allow the rocket to use booster ignition and throttle, like action = [0, 0, 0, 1, 1, 0, 0], but I got speed on x and y, like linear velocity = [0.3, 0.4, 0.5] instead of [0, 0, 0.5].
I think I cannot find the detail in your published paper.

**Comment by jjshoots** [comment]
By default, you will not be able to land the rocket with only vertical actuators (only throttle nd ignition) since the rocket starts in an arbitrary rotated orientation and there is also output noise. You can disable those here:
- [Set `randomize_drop=False` here](https://github.com/jjshoots/PyFlyt/blob/master/PyFlyt/gym_envs/rocket_envs/rocket_landing_env.py#L100)
- [Set `noise_ratio=0` here](https://github.com/jjshoots/PyFlyt/blob/master/PyFlyt/models/vehicles/rocket/rocket.yaml#L19)
- [Pin the landing pad position here](https://github.com/jjshoots/PyFlyt/blob/master/PyFlyt/gym_envs/rocket_envs/rocket_landing_env.py#L116-L120)

There may still be some level of noise in the system, but disabling those settings should make things much easier.

If you'd like to start tweaking the reward structure, it is defined [here](https://github.com/jjshoots/PyFlyt/blob/master/PyFlyt/gym_envs/rocket_envs/rocket_landing_env.py#L192).

**Comment by Pytha11** [comment]
I split the landing into two simple tasks to help me find the potential reward design.
vertical landing                      and        "horizontal" landing 
        o (start position)                                   o 
        *                                                                  *
        *                                                                        *
       O (target position)                                                    O
Could you help me to give some demonstrations of action for agent with expert knowledge on how to successfully land in the "horizontal" landing?

**Comment by jjshoots** [comment]
Hi, sorry for the super late reply. I don't actually have demonstrations of a successful horizontal landing, but I would imagine that some level of gliding is required. The rocket body is represented as a `boring_body`, and hence can actually produce lift/drag depending on orientation.

**Comment by jjshoots** [comment]
Do you happen to have a video of the landing?

**Comment by Pytha11** [comment]
Uploading Bullet Physics ExampleBrowser using OpenGL3+ [btgl] Release build 2024-11-27 11-53-03.mp4…

![image](https://github.com/user-attachments/assets/3bfa0571-7c0a-46ae-9fe5-6e7a3e0fe9a7)
![image](https://github.com/user-attachments/assets/2b9b34d2-7e57-4ace-b613-425a7117b15f)

**Comment by jet-sony** [comment]
First off, that video and the graph looks amazing. For the issue of the algorithm exploiting the velocity reward when away from the pad, one solution I can imagine is slightly increasing the horizontal offset penalty, and increase the final landing reward slightly. We essentially need to encourage the agent that high offset is a bad thing. I would actually propose using a binary constant penalty for this, induced when the rocket is x distance away from the pad (probably x = pad radius).

**Comment by Pytha11** [comment]
I only disable your rewards for each step and add a negative abs(speed at z axis) as a reward for each terminal of an episode (like sparse reward). Moreover, I only use booster ignition and throttle for the vertical landing task. It makes rocket landing as a simple task so that PPO can find out the appropriate solution. For landing with other conditions, I still fail to make it.

**Comment by jjshoots** [comment]
I have fixed the environment in #68, it should be learnable now. I have also made a new release with this fix.
